version: "3.8"

services:
  php:
    build: php-fpm
    ports:
      - '9002:9000'
    links:
      - db
    volumes:
      - ../application:/var/www/application:cached
  nginx:
    build: nginx
    ports:
      - '8080:80'
    links:
      - php
      - db
  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
